### ISSUE TITLE
年齢の表示について

### ISSUE THREAD

**Issue by TOBE-ASUNARO** [RaiseTech-team01/reservation_app#130]
APIで、生年月日で戻り値をえている　YYYYMMDD形式
年齢で表示するなら、生年月日から、表示日時での計算が必要。

対応案ですが、
A)　ページのラベルを「年齢」から「生年月日」表示を変更する（簡単）

B)　APIレベルで、生年月日を返すところを、年齢も計算して返す

とりあえず、A)で対応して、B)まで行いますかね。
店サイドは、年齢がわかったほうが、使いやすい気はします。。。

**Comment by KazusaNakagawa** [comment]
@TOBE-ASUNARO
そうですね。年齢表示で対応が普通ですね。
Issues 作成ありがとうございます。実装ロジックを考えてみます!

**Comment by yukinkomob** [comment]
下記で対応を行い、PRに上げました
https://github.com/RaiseTech-team01/reservation_app/pull/157
