### ISSUE TITLE
画面更新時にログイン状態を維持できない

### ISSUE THREAD

**Issue by yukinkomob** [RaiseTech-team01/reservation_app#154]
## 背景

- 現状は、ログイン後にログイン必須の画面にアクセス可能になる
- ログイン必須の画面から他の同様の画面への画面遷移は正常に行われている
- しかし、画面更新をするとその画面からログイン画面への遷移が行われてしまい、再度ログイン情報の入力を要求される

## 問題点

- ログイン成功後にアカウント情報画面に遷移した後、画面更新をするとログイン画面に遷移してしまう

## 期待動作

- ログイン状態を維持し、画面更新時にその画面に留まること

**Comment by TOBE-ASUNARO** [comment]
フロントで対応した部分ですが、少し前で、忘れかけていますが、

ログインの状態管理はVuexで、行っています。
(auth.jsのisLogin)

また、Vuexは、セッションが切れると、状態管理していたデータを失います。セッションが失われると(=ログインした状態でなくなると)、ログイン画面に遷移するような、、、。

たしか、、、ログイン状態を復帰させる処理は、自身の情報を読み出すAPIがないと、難しい気がして、ログイン画面へ遷移するようにしたと思います。

このあたりのベストな対応はよくわからず、比較的安全に、セキュアに動作するようにしたと思います。

**Comment by yukinkomob** [comment]
@TOBE-ASUNARO 

なるほど。Vuexで状態管理をしていたのですね。ありがとうございます。

現状では、ログイン状態を復帰する処理は実装されておらず、一律ログイン画面に遷移する実装になっている、ということですね。
セッションの期限は2週間だったと思うので、今回は期限切れということはなさそうですね。

修正後に確認のために画面更新をする度に、ログイン画面に遷移するという挙動が発生するため、優先的に解決したいと思っています。とりあえず、強制画面遷移を外しておこうかと。

自身の情報を読み出すAPIとは、ログイン状態をチェックするAPIのようなものがあればいいのでしょうか。
例えば、uid, client, access-tokenをbodyとしてpostするAPIの応答がログイン状態有無であるなど。

後調べてみたところ、router.js の画面ごとのパラメータに isPublicを追加して、trueの場合は未ログインでもアクセスOK、falseの場合はログイン必須、などと区別させる方法もあるようです。これならsecureな画面とそれ以外が一瞥できるので、便利そうですね。
対応を検討してみようかなと思っています。

**Comment by yukinkomob** [comment]
> router.js の画面ごとのパラメータに isPublicを追加して、trueの場合は未ログインでもアクセスOK、falseの場合はログイン必須、などと区別させる方法

下記を参考にしました。
https://qiita.com/takatama/items/05e9fbc7199cde4caf60

**Comment by yukinkomob** [comment]
未ログイン状態の場合のリダイレクト自体はサーバ側で行われているようでした。
Cookie情報が渡されていないのが原因ではないかと考え、下記のIssueを登録しました。
https://github.com/RaiseTech-team01/reservation_app/issues/167

**Comment by TOBE-ASUNARO** [comment]
> 現状では、ログイン状態を復帰する処理は実装されておらず、一律ログイン画面に遷移する実装になっている、ということですね。

そうです。たしか再度ログインさせるようにしました。

> セッションの期限は2週間だったと思うので、今回は期限切れということはなさそうですね。
> 

セッションとは、その都度の、接続の確立から終了までをさしています。2週間の期限は、deviceトークンの３セットの有効期限だったでしょうか？？

> 修正後に確認のために画面更新をする度に、ログイン画面に遷移するという挙動が発生するため、優先的に解決したいと思っています。とりあえず、強制画面遷移を外しておこうかと。
>

> 自身の情報を読み出すAPIとは、ログイン状態をチェックするAPIのようなものがあればいいのでしょうか。
> 例えば、uid, client, access-tokenをbodyとしてpostするAPIの応答がログイン状態有無であるなど。
例えば、uid, client, access-tokenをヘッダーにいれて、getで、ユーザー情報がとれるようなイメージです。

> 後調べてみたところ、router.js の画面ごとのパラメータに isPublicを追加して、trueの場合は未ログインでもアクセスOK、falseの場合はログイン必須、などと区別させる方法もあるようです。これならsecureな画面とそれ以外が一瞥できるので、便利そうですね。
> 対応を検討してみようかなと思っています。

いいですね。

**Comment by TOBE-ASUNARO** [comment]
> 未ログイン状態の場合のリダイレクト自体はサーバ側で行われているようでした。
> Cookie情報が渡されていないのが原因ではないかと考え、下記のIssueを登録しました。
> #167

JS側のログイン判定は、トークンの有無で判断するようにしたと思います。
その状態をVuexで管理（＝セッションごとで、ログイン状態を一時的に記憶させています）

**Comment by yukinkomob** [comment]
@TOBE-ASUNARO 

> 現状では、ログイン状態を復帰する処理は実装されておらず、一律ログイン画面に遷移する実装に> なっている、ということですね。

> そうです。たしか再度ログインさせるようにしました。

これはログイン画面に遷移するという意味ですか？
それとも再ログイン処理を実行させているという意味ですか？

**Comment by yukinkomob** [comment]
> セッションとは、その都度の、接続の確立から終了までをさしています。2週間の期限は、deviceトークンの３セットの有効期限だったでしょうか？？

セッションについては了解ですが、期限については前に加藤さんから聞いた内容になります。細かいところは自分の記憶から抜けているかもですが。。

**Comment by yukinkomob** [comment]
> 後調べてみたところ、router.js の画面ごとのパラメータに isPublicを追加して、trueの場合は未ログインでもアクセスOK、falseの場合はログイン必須、などと区別させる方法もあるようです。これならsecureな画面とそれ以外が一瞥できるので、便利そうですね。
> 対応を検討してみようかなと思っています。

> いいですね。

この辺り、セキュアな画面かどうかはサーバ側で区別しているようでした。
そのため、クライアント側では特に対応する必要はなさそうです。
Cookieのやり取りがないのが原因かなあ？と思ったので、
#167
に登録しました。まずはこちらの対応待ちですね。

**Comment by TOBE-ASUNARO** [comment]
> > そうです。たしか再度ログインさせるようにしました。
> 
> これはログイン画面に遷移するという意味ですか？
> 
> それとも再ログイン処理を実行させているという意味ですか？

ログイン画面に遷移するという意味です。

**Comment by yukinkomob** [comment]
制限事項
