### ISSUE TITLE
デザイン修正のためのコンポーネント分割

### ISSUE THREAD

**Issue by yukinkomob** [RaiseTech-team01/reservation_app#155]
## 背景

* 今後デザインを改善するとして、改善案を適用する際に今のVueのコードでは重複箇所が多いため、延々と置き換え作業をすることになる
* 共通している部分は部品として切り出して、それを再利用する形にすることで、デザイン再適用時の作業を減少することができる
    * 例えば、今は各画面ごとにbutton要素を配置してスタイルを個々に設定しているが、ボタンをコンポーネントとして切り出すことで、それを使い回すことができ、スタイルの修正が必要になったら１箇所を修正すれば済むようになる。
* コンポーネント分割には色々なやり方があるが、当面の目的としては再利用性を上げて、画面間で重複する部分を減らすことを目指したい

## 問題点

* コンポーネントの粒度が大きく、画面間の重複箇所が多い

## 期待動作

* コンポーネントの粒度を小さくし、再利用性を高める

**Comment by yukinkomob** [comment]
コンポーネントを分割する前にファイルの構成を作っておきたい
ファイルの構成をする前に相対パスだらけの状況を何とかしたい

**Comment by yukinkomob** [comment]
* 相対パスを絶対パスに変換するための事前準備としてファイルパスのエイリアスを設定
* エイリアスを利用して相対パスを絶対パスに変換
* components/storeフォルダ以下のファイルをcomponents/pages/store/以下に再配置
* StoreFooterをコンポーネントとして切り出し

https://github.com/RaiseTech-team01/reservation_app/tree/issue155-divide-components

**Comment by TOBE-ASUNARO** [comment]
CSSのスコープ、後出し優先。
解決の一つにFLOCSS。

装飾にtailwindを選んでるので、ユーティリティファーストに、なるのかな？

メンタのメンターさんのアドバイスに興味があります。

**Comment by yukinkomob** [comment]
対応不要
