### ISSUE TITLE
API動作の調査

### ISSUE THREAD

**Issue by yukinkomob** [RaiseTech-team01/reservation_app#161]
APIを叩いた結果を一覧表にまとめる

**Comment by TOBE-ASUNARO** [comment]
まとめるなら、OpenAPIなどの仕様を使うとよいのかな。

https://future-architect.github.io/articles/20191008/

https://gift-tech.co.jp/articles/round-up-openapi-tools/

**Comment by yukinkomob** [comment]
Swaggerは、なかなか見栄えがいいし、情報を参照しやすいと思います。
ちょっとやってみようかなと思います。

**Comment by yukinkomob** [comment]
こちらではAPIの動作確認を主に行います。

Swaggerなどでまとめる作業は下記。
https://github.com/RaiseTech-team01/reservation_app/issues/190

**Comment by yukinkomob** [comment]
完了
