### ISSUE TITLE
現行デザインのブラッシュアップ

### ISSUE THREAD

**Issue by yukinkomob** [RaiseTech-team01/reservation_app#178]
現行デザインをベースに可能な限りブラッシュアップを試みる。
主に色合い、配置、装飾などに手を加えて、大きな変更はせずに見られるレベルの状態になることを目指す。

メモ
https://docs.google.com/spreadsheets/d/1POQ7S6QJxd8R9bJ12MEOhO_Yzr0OdxVsZVJyQji8pCo/edit#gid=0

**Comment by yukinkomob** [comment]
ボタンやフォームなどの共通パーツはコンポーネント化を試みる。
TailwindCSSのconfigを利用して、よく使うプロパティについては定数化を行い、後から修正しやすい状態にする。

**Comment by yukinkomob** [comment]
MENTAを介して知ったデザイナーのかとうまきこさんにデザインレビューが可能か問い合わせ中です。
https://menta.work/plan/1132

今後、下記のサイクルをデザインが一定の水準になるまで繰り返す予定です。

1. MENTAにてデザイナーを検索
2. デザインレビューを依頼
3. デザインレビューで指摘された箇所を修正
4. チーム内にて共有
5. 1に戻る

**Comment by TOBE-ASUNARO** [comment]
さすがです！

**Comment by yukinkomob** [comment]
デザインレビューの結果が来ました。
こちらを基に修正につなげていきます。

[デザインレビュー_かとうまいこさん-20210820.pdf](https://github.com/RaiseTech-team01/reservation_app/files/7020869/_.-20210820.pdf)

**Comment by yukinkomob** [comment]
## レビュー指摘内容

### 文字色・文字サイズ

* 色のメリハリを付ける
    * リンク、ボタン、見出しなどの全てが同色になっている
    * クリッカブルな文字と非クリッカブルな文字は色を分ける
* 文字のジャンプ率を付ける
    * ジャンプ率とは「本文の文字サイズに対する見出しの文字サイズの比率」のこと
    * 適切なフォントサイズに設定する

### 配色

* 背景色のグレーが濃い
* header, footerの色が黄色と黒の配色できつい（警告色の組み合わせとのこと）
* ボタンの色が単一色で区別がつかない
    * 全て黄色
* グローバルナビの赤色がきつい

### アカウント情報ページ

* アカウント設定だけ太文字なのはなぜ？ => 修正済み
* パンくずリストの「アカウント情報」とナビの「アカウント設定」が表記ゆれ => 修正済み
* th要素の「メールアドレス」「電話番号」の文字サイズが他と異なるのが違和感
* グローバルナビのネーミングを分かりやすくする
    * 例：予約する | 予約中 | 利用履歴 | アカウント設定

### 予約登録ページ

* 予約フローの高さが高すぎて、情報が押し出されている
* 個人情報保護方針への導線がない

### 予約一覧ページと予約履歴ページ

* どちらのページも表示が同じであり、違和感がある => 予約履歴は削除済み
* カレント表示がなく、ページ見出しがないため、迷子になりやすい => カレント表示を追加済み
* 全体的にデザイン要素が少なく、ただテキストを並べただけという感じ
    * 人数：3名の人数の部分をラベル表示にするなど、見やすくする工夫を

### その他

* ヘッダーのアイコンはアカウント設定やマイページへ遷移するというイメージがある
* ログアウトに移行するのに2クリック必要なので、最初からログアウトというテキストリンクでもいいかも
* グローバルナビにアイコン表示があると分かりやすいのでは
* 全体的な余白が狭い
    * グローバルナビと比べてメインコンテンツ幅が狭い
    * メインコンテンツの内側余白（padding）も狭い
* 予約履歴なのに予約情報が変更可能になっているのはおかしいのでは？

**Comment by yukinkomob** [comment]
### 修正案１

* 配色はRaiseTechのHPを参考
* 色合いなどを変更
* フォントを変更
* ナビのラベル名を変更
* 左上にロゴっぽいのを配置

<img src="https://user-images.githubusercontent.com/3205581/130307887-4a6ebb0e-4911-484c-b0be-9b54700f859d.png" width="400px">

**Comment by yukinkomob** [comment]
現状は改善
