### ISSUE TITLE
[test#3] 「次からは自動でログインする」機能の仕様検討

### ISSUE THREAD

**Issue by yukinkomob** [RaiseTech-team01/reservation_app#185]
### 再現手順

1. ログアウトする
2. アカウント情報画面のURLを入力して開く

### 期待動作

自動的にログインしてアカウント情報画面へ遷移

### 現状動作

動作が不明瞭
ログアウトした場合は自動ログインは効かせるべきではない？

### 試験表

No.3
https://docs.google.com/spreadsheets/d/1BPA1XvKjCI5xCO64HzYPSacxaORcCMk6zNqoKMFAknE/edit#gid=1804442586

**Comment by yukinkomob** [comment]
仕様の検討不足で具体的に何をすべきかが不明確なため、必要な検討を行う

**Comment by TOBE-ASUNARO** [comment]
ログイン・ログアウトのJS処理を担当しました。

ログインは、deviceのトークン３セットを、ローカルストレージに格納されたことをもって、ログインとしています。

ヘッダーのログアウトを選択した場合、ローカルストレージに格納されているdeviceのトークン３セットを、
破棄する動作にしました。

ログアウトを選択しない場合は、ローカルストレージにトークンが残ります。（クッキーのように残る）

よって、ローカルストレージにトークン３セットが、残っている限りは、ログイン状態と判定すると思います。

**Comment by yukinkomob** [comment]
失礼しました。この再現手順だと明確にログアウトしているので確かに再ログインはしないですね。

ログアウトではなく、予約アプリを表示しているブラウザタブを閉じて、再度予約アプリにアクセス、などとした場合が該当するかと思いました。

**Comment by TOBE-ASUNARO** [comment]
ブラウザのローカルストレージにデータの有る無しで、ログイン状態の判定しており、￼タブを閉じた際に、各ブラウザのローカルストレージの挙動によります。

プライベートモードなどブラウザの設定で変わる部分かも知れません。

**Comment by yukinkomob** [comment]
なるほど。Railsサーバ側でもログインページへのリダイレクト処理をしていたりするので、サーバ、クライアント両方でやっているという感じですね。ログイン状態の判定は主にヘッダの人型アイコンの状態設定に利用していると認識していました。
プライベートモードでアプリにアクセスする場合は、新たにログインの必要があるかと思います。

シークレット ブラウジングの動作の特徴
----
閲覧履歴、Cookie とサイトのデータ、フォームへの入力情報は保存されません。
ダウンロードしたファイルと作成したブックマークは保持されます。
アクセス先のウェブサイト、雇用主、学校、ご利用のインターネット サービス プロバイダには、閲覧内容を知られる可能性があります。
https://support.google.com/chrome/answer/95464?hl=ja&co=GENIE.Platform%3DDesktop

**Comment by yukinkomob** [comment]
制限事項
