### ISSUE TITLE
[test#9] アカウント入力画面でエラーを出力した後、前の画面に戻って再度アカウント入力画面を表示するとエラーと入力情報が残ったままになっている

### ISSUE THREAD

**Issue by yukinkomob** [RaiseTech-team01/reservation_app#186]
### 再現手順

1. 戻るボタンを押下

### 期待動作

ログイン画面へ遷移

### 現状動作

エラー出して、前の画面に戻った後にまたアカウント登録画面に遷移すると、エラーと入力内容がそのままになっている。

### 試験表

No.9
https://docs.google.com/spreadsheets/d/1BPA1XvKjCI5xCO64HzYPSacxaORcCMk6zNqoKMFAknE/edit#gid=1804442586

**Comment by TOBE-ASUNARO** [comment]
客側のアカウント登録を担当しました。RegistrationForm.vue

バリデーションでエラーになった場合、再入力の手間を減らすため、入力内容を復帰するようにしてあります。

**Comment by yukinkomob** [comment]
> アカウント入力画面でエラーを出力した後、前の画面に戻って再度アカウント入力画面を表示するとエラーと入力情報が残ったままになっている

書き方が不足しておりました。すみません。

こういう手順ですね。

1. アカウント入力画面で入力
2. アカウント確認画面に遷移
3. 登録ボタンを押下
4. アカウント入力画面に遷移し、画面内でエラー表示
5. 戻るボタンを押下して前の画面に遷移（アカウント情報画面など）
6. 再度アカウント入力画面に遷移
7. 前回の入力内容とエラー情報が表示されたままになっている

確認画面 -> 入力画面 に遷移した時に前の入力内容があるのはいいのですが、予約入力関連画面以外の画面 -> 入力画面 に遷移した時には、入力内容とエラー情報は消去しておこうかと思っています。

**Comment by TOBE-ASUNARO** [comment]
お願いします
