### ISSUE TITLE
[test#43] アカウント設定画面の保存ボタンを押下しても情報が更新されていない

### ISSUE THREAD

**Issue by yukinkomob** [RaiseTech-team01/reservation_app#187]
### 再現手順

1. 任意の入力フォームの値を変更
2. 保存ボタンを押下

### 期待動作

アカウント設定画面に表示される値が更新されていること

### 現状動作

更新されていない

### 試験表

No.43
https://docs.google.com/spreadsheets/d/1woNq5pu_R2pAGxKdaVEmPIRqynzITjRbLig_UM6UiiM/edit#gid=2118784304

**Comment by TOBE-ASUNARO** [comment]
客側のアカウント表示のJSの担当しました。AccountInfo.vue

いくつかの段階がありますが、
１）客側のアカウント表示は、内容を、Vuexから連れてくるので、Vuexにデータが格納されていますでしょうか？
２）Vuexの元データは、データベースから引っ張っています。変更したデータが、データベースに登録されていますでしょうか？
