### ISSUE TITLE
OpenAPIでAPI仕様をまとめてみる

### ISSUE THREAD

**Issue by yukinkomob** [RaiseTech-team01/reservation_app#190]
https://github.com/RaiseTech-team01/reservation_app/issues/161
からの派生

試しにやってみます。

参考：
https://future-architect.github.io/articles/20191008/
https://gift-tech.co.jp/articles/round-up-openapi-tools/

**Comment by TOBE-ASUNARO** [comment]
エディターは、Stoplight Studioが、簡単そう

**Comment by yukinkomob** [comment]
検討してみます。

**Comment by yukinkomob** [comment]
https://future-architect.github.io/articles/20191008/

内容を確認。
IDE（Stoplight Studio）を利用してSwagger APIの定義を行うことができ、それを元に擬似サーバ（Prism mock server）を利用して、APIのモックを実装することが可能（サーバ側にAPIが用意されていない場合でも、モックを叩いて結果を受信することができる）。
加えて、テストツール（Dredd）を用いて実際のAPIのテストを行うことができる。CI/CDツールと組み合わせて継続的テストを実行することも可能。

**Comment by yukinkomob** [comment]
試しにStoplight StudioのWorkspaceを作成してみました。（アカウント作成が必要ですが、誰でもアクセス可能です）
https://rt-team1.stoplight.io/settings/reservationapp

いくつかのAPIの登録を行いました。
中川さんの資料を基に割とスムーズに登録できました。
yaml形式ですが、コードを書く必要はなく、全てフォーム入力で行うことが可能でした。

**Comment by TOBE-ASUNARO** [comment]
The workspace administrators have received a notification of your request to join the workspace. You will receive an email once your request has been approved.

登録しました。承認依頼が飛んだと思います。よろしくお願いします。

**Comment by yukinkomob** [comment]
承認しました。どうでしょうか。

**Comment by yukinkomob** [comment]
2つのメールアドレスから来ましたが、両方加藤さんですか？
両方承認が必要でしょうか？

**Comment by yukinkomob** [comment]
bu*******@gmail.com
gh*****@**.asunaro-work.com

**Comment by yukinkomob** [comment]
ワークスペースの方は閲覧人数に制限があるようで。
https://rt-team1.stoplight.io/admin/billing
またちょっと調べてみます。

**Comment by yukinkomob** [comment]
これは法人向けのワークスペースのようですね。費用がちと高い。（現状はフリープラン）
個人向けがあるのかどうか分かりませんが。。

**Comment by TOBE-ASUNARO** [comment]
両方とも私です。一旦、削除してもらって構わないです。

とーっても、みやすいですね。ただ３人までなんですね。。。

**Comment by TOBE-ASUNARO** [comment]
作成データはファイルのエクスポートで保存できるようです。
とりあえずは、githubでエクスポートしたファイルを共有してIDEで開くとよいかも。

**Comment by yukinkomob** [comment]
了解です。一旦削除いたしました。
Google Driveみたいに誰でも見れる設定にできればいいのですが。

**Comment by yukinkomob** [comment]
確認済み
