### ISSUE TITLE
時間帯ピッカーを選択しても値が反映されない

### ISSUE THREAD

**Issue by yukinkomob** [RaiseTech-team01/reservation_app#196]
加藤さんからの下記の報告に関する調査

```
私の方で客側の予約登録を実装していこうと思います。
すでに客側の予約作成、編集用で、共通入力フォームを、作られていると思います。
確か、日にちのピッカーは実装されていて、その後、時間ピッカーも追加で実装されたと思います。
現在、私の方では、日にちは、ピッカーの選択が画面上でテキストボックスに反映されますが、時間ピッカーが反映されません。
developブランチに、先ほど行った、私のマージが、悪さしたと思っています。
いろいろと、触ってみましたが、お手上げ状態です。

大変申し訳ありまが、お時間あれば、現在のdevelopブランチで、時間ピッカーの挙動、コードを確認していただけないでしょうか？
```

**Comment by yukinkomob** [comment]
develop (#ef83280d)  を使用して再現確認。
しかし、なぜか問題が再現しない。
他の人の環境では再現するようなので、実装者側のみが行っている対応が存在しており、かつそれがレポジトリには反映されていない？

**Comment by yukinkomob** [comment]
### ログを追加したレポジトリ

https://github.com/RaiseTech-team01/reservation_app/tree/log/i178-timetable-log

### 再現確認時の動画

https://user-images.githubusercontent.com/3205581/130318059-0c2f2fae-7319-41a3-9a6f-57ef42c76c58.mp4

**Comment by yukinkomob** [comment]
@TOBE-ASUNARO 

私の環境では再現していないようです。
もしかしたら、実装時にローカルで何らかの対応が入っている可能性があるかも知れませんが、特定できていません。すみません。

再現時の状況を確認したいので、上記のログを追加したレポジトリを用いて、再現時のコンソールログを取得して頂けませんでしょうか。

1. 時間帯ピッカーのダイアログオープン時に出力されるログ
2. 時間帯選択時に出力されるログ

ログの出力状況は上記の動画を参考にしてください。
お手数おかけして申し訳ありませんが、よろしくお願いいたします。

**Comment by yukinkomob** [comment]
@TOBE-ASUNARO 

確認後に問題なければ、こちらcloseでお願いします。

**Comment by yukinkomob** [comment]
MTGにて

こちらは対応済みで、既にマージされたとのこと。

**Comment by yukinkomob** [comment]
加藤さんの環境にて、時間帯ダイアログを立ち上げるのに2回選択ボックスをクリックする必要があるとのことで、再オープン。

**Comment by TOBE-ASUNARO** [comment]
vue.runtime.esm.js:638 [Vue warn]: Invalid prop: type check failed for prop "bcList". Expected Object, got Array 

found in

---> <BreadClumbList> at app/javascript/components/commons/layouts/BreadClumbList.vue
       <ReservationInputs> at app/javascript/components/layout/ReservationInputs.vue
         <ReservationForm> at app/javascript/components/ReservationForm.vue
           <App> at app/javascript/app.vue
             <Root>
warn @ vue.runtime.esm.js:638
assertProp @ vue.runtime.esm.js:1726
validateProp @ vue.runtime.esm.js:1662
updateChildComponent @ vue.runtime.esm.js:4126
prepatch @ vue.runtime.esm.js:3123
patchVnode @ vue.runtime.esm.js:6306
updateChildren @ vue.runtime.esm.js:6190
patchVnode @ vue.runtime.esm.js:6325
updateChildren @ vue.runtime.esm.js:6190
patchVnode @ vue.runtime.esm.js:6325
patch @ vue.runtime.esm.js:6507
Vue._update @ vue.runtime.esm.js:3932
updateComponent @ vue.runtime.esm.js:4056
get @ vue.runtime.esm.js:4470
run @ vue.runtime.esm.js:4556
flushSchedulerQueue @ vue.runtime.esm.js:4304
(anonymous) @ vue.runtime.esm.js:2023
flushCallbacks @ vue.runtime.esm.js:1945
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1973
nextTick @ vue.runtime.esm.js:2034
queueWatcher @ vue.runtime.esm.js:4400
update @ vue.runtime.esm.js:4545
notify @ vue.runtime.esm.js:756
reactiveSetter @ vue.runtime.esm.js:1081
setTime @ ReservationInputs.vue:483
updateDate @ ReservationForm.vue:72
handleDateClick @ FullCalendarDialog.vue:75
Emitter.trigger @ main.js:5785
DateClicking._this.handleDragEnd @ main.js:1420
Emitter.trigger @ main.js:5785
HitDragging.handleDragEnd @ main.js:1223
Emitter.trigger @ main.js:5785
FeaturefulElementDragging.stopDrag @ main.js:1050
done @ main.js:416
setTimeout (async)
ElementMirror.stop @ main.js:424
FeaturefulElementDragging.tryStopDrag @ main.js:1045
FeaturefulElementDragging._this.onPointerUp @ main.js:971
Emitter.trigger @ main.js:5785
PointerDragging.handleMouseUp @ main.js:76

**Comment by TOBE-ASUNARO** [comment]
これが、2021/08/22のDevelopブランチからです。
一回目のクリックでは、コンソールにlogは、でませんでした。
２回目のクリックで、時間帯のピッカーがせり出す。
ピッカーのクリック後、上記のログが、コンソールログに出力されました。

**Comment by TOBE-ASUNARO** [comment]
**firefox(linux)は、ワンクリックでできました。**
chrome(linux)の固有の問題でしょうか。。。。

**Comment by yukinkomob** [comment]
現状は改善
