### ISSUE TITLE
.env file lost?

### ISSUE THREAD

**Issue by TOBE-ASUNARO** [RaiseTech-team01/reservation_app#36]
.env ファイルが、.gitignoreに含まれています。フィアルを残して、内容のコメントアウトで対応するほうが、便利な気がします。ご検討ください。

**Comment by KazusaNakagawa** [comment]
そうですね。見えない方が良いと判断して、 `.gitignore` にしておりました。
開発段階では、オープンでも良さそうですかね??

Git 管理下に戻しておきます👏

**Comment by KazusaNakagawa** [comment]
@TOBE-ASUNARO 

Git管理下にしました。確認お願いします。

問題なければ、本件 **Close** として頂ければ幸いです。

**Comment by TOBE-ASUNARO** [comment]
ありがとうございます。あってもないレベルのPWなので、いいですよね？？

**Comment by KazusaNakagawa** [comment]
いんじゃ閉めますね

**Comment by KazusaNakagawa** [comment]
公開してはいけない環境変数を追加したら、git 管理外に戻す

**Comment by KazusaNakagawa** [comment]
対応しました。https://github.com/RaiseTech-team01/reservation_app/pull/49/commits/aad143f4d7c06c0164370f1546d17ed801fc6eb5

**Comment by KazusaNakagawa** [comment]
対応しました。https://github.com/RaiseTech-team01/reservation_app/pull/49/commits/aad143f4d7c06c0164370f1546d17ed801fc6eb5
