### ISSUE TITLE
R18_予約機能_予約検索機能

### ISSUE THREAD

**Issue by TOBE-ASUNARO** [RaiseTech-team01/reservation_app#50]
前回、HELPを依頼したが、Katoが、時間がとれず進捗なし。
まずはブランチだけ切る。

チケットをみると、検索機能とあるが、
予約作成、予約検索、etcの複数の機能を実装するように思われる。
＝＞部内で確認して、開発の機能を明確にして、すすめることとする。

Slackで相談しますね。

**Comment by KazusaNakagawa** [comment]
お願いします!!

**Comment by KazusaNakagawa** [comment]
実装中です。

**Comment by KazusaNakagawa** [comment]
#70 で実装一旦完了
